import { Inter, Gaegu } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const gaegu = Gaegu({
  subsets: [],
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={gaegu.className}>{children}</body>
      </html>
  );
}
